#!/usr/bin/env python

import sys, socket

BUFFER_SIZE = 20  # Normally 1024, but we want fast response

def main(ip, port):
    port = int(port)

    print 'TCP listen on %s:%d' % (ip, port)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.bind((ip, port))
    s.listen(1)

    conn, addr = s.accept()
    print 'connection from %s:%d' % addr
    while 1:
        data = conn.recv(BUFFER_SIZE)
        if not data: break
        print "received %r" % (data,)
        conn.send(data)  # echo
    conn.close()

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'usage: %s IP PORT' % sys.argv[0]
    else:
        main(*sys.argv[1:])
