#!/usr/bin/env python

import sys, socket

def main(ip, port):
    port = int(port)

    print 'UDP listen on %s:%d' % (ip, port)

    sock = socket.socket(socket.AF_INET, # Internet
                         socket.SOCK_DGRAM) # UDP
    sock.bind((ip, port))

    while True:
        data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
        print "received from %s:%d: %r" % (addr[0], addr[1], data)
    
if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'usage: %s IP PORT' % sys.argv[0]
    else:
        main(*sys.argv[1:])
