#!/usr/bin/env python

import sys, socket

MESSAGE = "Hello, World!"

def main(ip, port):
    port = int(port)
    print 'sending to %s:%d' % (ip, port)
    print "message %r" % (MESSAGE,)
    sock = socket.socket(socket.AF_INET, # Internet
                         socket.SOCK_DGRAM) # UDP
    sock.sendto(MESSAGE, (ip, port))

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print 'usage: %s IP PORT' % sys.argv[0]
    else:
        main(*sys.argv[1:])
